name: CI/CD Pipeline - Backend

on:
  push:
    branches:
      - feat/addnew-backend-version

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Clonar repositÃ³rio
        uses: actions/checkout@v3

      - name: â˜•ï¸ Instalar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: ğŸ› ï¸ Compilar o projeto
        run: ./mvnw clean package -DskipTests

      - name: ğŸ§ª Executar testes
        run: ./mvnw test

      - name: ğŸ³ Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ğŸ“¦ Gerar imagem Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/springbackend:latest .

      - name: ğŸ“¤ Publicar no Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/springbackend:latest
